#!/bin/bash

# Available Colors
black='\033[0;30m'
red='\033[0;31m'
green='\033[0;32m'
brown='\033[0;33m'
blue='\033[0;34m'
purple='\033[0;35m'
cyan='\033[0;36m'
gray='\033[0;37m'

bold='\e[1m'
none='\033[0m'

#----------------------------------------------------------
#                        Settings
#----------------------------------------------------------

# From what exchange do you want prices to be fetched?
# 0 = Coinbase
# 1 = Binance (Default)
exchange=1

# Provide all cryptocurrencies that you hodl
cryptoCurrencies=("BTC" "ETH" "IOTA" "TRX")

# Provide balance of all cryptocurrencies that you have stated in cryptoCurrencies
BTC=0.0126673
ETH=0.026984
IOTA=2191.50
TRX=1092.5

# Provide colors of all cryptocurrencies that you have stated in cryptoCurrencies
BTC_color=$brown
ETH_color=$blue
IOTA_color=$brown
TRX_color=$blue

#----------------------------------------------------------
#                    END of Settings
#----------------------------------------------------------

echo -e "${brown}"
echo "  _____                  _        ____        _ "
echo " / ____|                | |      |  _ \      | |"
echo "| |     _ __ _   _ _ __ | |_ ___ | |_) | __ _| |"
echo "| |    | '__| | | | '_ \| __/ _ \|  _ < / _\` | |"
echo "| |____| |  | |_| | |_) | || (_) | |_) | (_| | |"
echo " \_____|_|   \__, | .__/ \__\___/|____/ \__,_|_|"
echo "              __/ | |"
echo "             |___/|_|"
echo -e "${none}"

if [ $exchange == 1 ]
then
  prices=$(curl -s https://api.binance.com/api/v3/ticker/price)
else
  prices=$(curl -s https://api.coinbase.com/v2/exchange-rates?currency=USD)
fi

total=0

printf "%10s | %15s | %15s | %15s |" "Crypto" "Price" "Holdings" "Portfolio"
echo -e "\n-----------------------------------------------------------------|"
for i in ${!cryptoCurrencies[@]};
do
  CName=${cryptoCurrencies[$i]}

  if [ $exchange == 1 ]
  then
    CPrice=$(echo $prices | jq '.[] | select(.symbol=="'${CName}USDT'") | .price' | bc)
    CPrice=$(printf '%.2f' $CPrice)
  else
    CPrice=$(echo $prices | jq ".data.rates.$CName" | bc)
    CPrice=$(printf '%.18f' $CPrice)
    CPrice=$(echo "scale=2; 1/$CPrice" | bc)
  fi

  CPortfolio=$(echo "scale=2; $CPrice * ${!CName}" | bc)
  CPortfolio=$(printf '%.2f' $CPortfolio)
  total=$(echo "scale=2; $total + $CPortfolio" | bc)
  CPrice=$(printf "%'.2f" $CPrice)
  CPortfolio=$(printf "%'.2f" $CPortfolio)
  color=$(echo "${CName}_color")
  printf "${!color}${bold}%10s$none | %15s | %15s | %15s |" "$CName" "\$$CPrice" "${!CName} $CName" "\$${CPortfolio}"
  echo ""
done
echo -e "$none-----------------------------------------------------------------|"
total=$(printf "%'.2f" $total)
printf "${green}%10s $none| %15s   %15s  ${green}${bold} %15s $none|" "Total" "" "" "\$${total}"
echo -e "\n"